version: 2
updates:
  - package-ecosystem: gradle
    directory: /
    schedule:
      interval: daily
      timezone: Asia/Shanghai
    assignees:
      - xfqwdsj
  - package-ecosystem: github-actions
    directory: .github/workflows
    commit-message:
      prefix: ci
    schedule:
      interval: daily
      timezone: Asia/Shanghai
    assignees:
      - xfqwdsj
