name: Build and Release

on:
  push:
    branches:
      - main
    tags:
      - v*
  pull_request:
    branches:
      - main

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build-and-release:
    strategy:
      fail-fast: false
      matrix:
        include:
          - platform: Android, Linux, Web
            os: ubuntu-latest
          - platform: Windows
            os: windows-latest

    name: Build and Release ${{ matrix.platform }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup JDK
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: '21'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - if: matrix.os == 'ubuntu-latest'
        name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - if: matrix.os == 'ubuntu-latest'
        name: Configure Android signing
        shell: bash
        run: |
          if [ "${{ secrets.KEY }}" != "" ] && [ "${{ secrets.PROPERTIES }}" != "" ]; then
            cd compose-app
            echo ${{ secrets.KEY }} | base64 --decode > key.jks
            echo ${{ secrets.PROPERTIES }} | base64 --decode > key.properties
          fi

      - if: github.event_name == 'push' && github.ref_type == 'tag'
        name: Create release
        shell: bash
        continue-on-error: true
        run: |
          gh api \
            --method POST \
            -H "Accept: application/vnd.github+json" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            repos/${{ github.repository_owner }}/${{ github.event.repository.name }}/releases \
            -f tag_name=${{ github.ref_name }} \
            -F generate_release_notes=true
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Build ${{ matrix.platform }} app
        shell: bash
        run: |
          ./gradlew ciReleaseApp

      - name: Upload ${{ matrix.platform }} app
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.platform }} app
          path: build/assets/*

      - if: github.event_name == 'push' && matrix.platform == 'Android, Linux, Web'
        name: Upload Pages artifact
        id: deployment
        uses: actions/upload-pages-artifact@v3
        with:
          path: build/assets/web

      - if: github.event_name == 'push' && github.ref_type == 'tag'
        name: Release
        uses: svenstaro/upload-release-action@v2
        with:
          tag: refs/tags/${{ github.ref_name }}
          file: build/assets/*
          file_glob: true
  deploy-to-pages:
    needs: build-and-release
    name: Deploy to GitHub Pages
    environment:
      name: Web Demo
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
